export const todoTasks = [
  {
    id: 1,
    tittle: "reading",
    assignee: "myself",
    dueDate: "2/5/2025",
    taskClass: "house",
    priority: "yes",
    completed: "no",
    description: "exam reading according to exam times table",
  },

  {
    id: 2,
    tittle: "wedding",
    assignee: "myself",
    dueDate: "2/12/2025",
    taskClass: "task",
    priority: "no",
    completed: "no",
    description: "kazeem wedding",
  },
  {
    id: 3,
    tittle: "e-commerce app",
    assignee: "myself",
    dueDate: "4/12/2025",
    taskClass: "work",
    priority: "yes",
    completed: "yes",
    description:
      "front-end design and development of jumial mobile and desktop app",
  },
  {
    id: 4,
    tittle: "wedding",
    assignee: "myself",
    dueDate: "7/12/2025",
    taskClass: "assigned",
    priority: "no",
    completed: "no",
    description: "kazeem wedding",
  },
  {
    id: 5,
    tittle: "reading",
    assignee: "myself",
    dueDate: "8/5/2025",
    taskClass: "personal",
    priority: "yes",
    completed: "yes",
    description: "exam reading according to exam times table",
  },
  {
    id: 6,
    tittle: "wedding",
    assignee: "myself",
    dueDate: "5/5/2025",
    taskClass: "social",
    priority: "no",
    completed: "no",
    description: "kazeem wedding",
  },
  {
    id: 7,
    tittle: "bank app project",
    assignee: "myself",
    dueDate: "4/12/2025",
    taskClass: "planned",
    priority: "yes",
    completed: "no",
    description:
      "front-end design and development for bank of nigeria mobile app",
  },
  {
    id: 8,
    tittle: "wedding",
    assignee: "myself",
    dueDate: "5/25/2025",
    taskClass: "friend",
    priority: "no",
    completed: "no",
    description: "kazeem wedding",
  },
];
